language: python
dist: trusty
os: linux
services:
- docker
python:
- '3.6'
install:
- pip install --upgrade .
script:
- flake8 atm
- pytest test
- coverage run --source=atm -m pytest test
after_success:
  - coverage report -m
notifications:
  email: false
